name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Restore dependencies
      run: dotnet restore WebApi/WebApi.sln
    - name: Build
      run: dotnet build WebApi/WebApi.sln --no-restore --output Release/
    - name: Ls dir
      run: ls
    - name: Deploy to IIS
      run: |
        iisreset /stop
        Copy-Item Release/* C:/gitactiontest -Recurse -Force
        iisreset /start
